### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bay334** [LiuzmNUDT/DNN-DOA#2]
Hi,
Can you help me?When I run the code of main_arrayimperfactions.py,the error appears.I can hardly solve it.
Help please!
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,90]
	 [[node Placeholder (defined at \graduate\论文\DNN-DOA-master\DNN-DOA-master\ensemble_model.py:15) ]]

**Comment by robert-m-taylor** [comment]
I had the same problem trying to get the code to work after translating it from TensorFlow 1 to TensorFlow 2.  The following corrections in "main_ArrayImperfections.py" fixed the problem for me:

            # data_batch = np.expand_dims(test_cov_vector, axis=-1)
            data_batch = np.expand_dims(test_cov_vector, axis=0)
            # feed_dict = {enmod_3.data_train: data_batch}
            feed_dict = {enmod_3.data_train_: data_batch}

**Comment by bay334** [comment]
> I had the same problem trying to get the code to work after translating it from TensorFlow 1 to TensorFlow 2. The following corrections in "main_ArrayImperfections.py" fixed the problem for me:
> 
> ```
>         # data_batch = np.expand_dims(test_cov_vector, axis=-1)
>         data_batch = np.expand_dims(test_cov_vector, axis=0)
>         # feed_dict = {enmod_3.data_train: data_batch}
>         feed_dict = {enmod_3.data_train_: data_batch}
> ```

Thanks a lot,solved.
My god,new error occurs.I am so confused about the new error.

Epoch: 299, Batch: 616, loss: 7.91852
Epoch: 299, Batch: 617, loss: 3.47653
testing...
Traceback (most recent call last):
  File "D:/graduate/论文/DNN-DOA-master/DNN-DOA-master/main_ArrayImperfections.py", line 171, in <module>
    model_path_ss=model_path_ss)
  File "D:\graduate\论文\DNN-DOA-master\DNN-DOA-master\ensemble_model.py", line 42, in __init__
    self.W_ec = tf.Variable(initial_value=var_dict_nn['W_ec:0'],
KeyError: 'W_ec:0'

**Comment by robert-m-taylor** [comment]
I don't get that KeyError.  I'm using Tensorflow 2.10.0 and used the "tf_upgrade_v2" command line script as described at https://www.tensorflow.org/guide/migrate/upgrade to migrate the code base before running.  It's possible that workflow could solve your problem.

**Comment by bay334** [comment]
> I don't get that KeyError. I'm using Tensorflow 2.10.0 and used the "tf_upgrade_v2" command line script as described at https://www.tensorflow.org/guide/migrate/upgrade to migrate the code base before running. It's possible that workflow could solve your problem.
Thanks a lot!
Can you share me some figures about this paper? My email is 2668670912@qq.com.

**Comment by anourbakhsh73** [comment]
@gicu8ab2 Hi. Can you share the translated code in TensorFlow 2 with me? Thanks

**Comment by cczujay** [comment]
Hi,
Can you help me?When I run the code of main_arrayimperfactions.py,the error appears.I can hardly solve it.
Help please!
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,90]
	 [[node Placeholder (defined at \CNN\Code\Python_CNN\ensemble_model.py:12) ]]
	 [[concat/_1]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,90]
	 [[node Placeholder (defined at \CNN\Code\Python_CNN\ensemble_model.py:12) ]]
0 successful operations.
0 derived errors ignored.

**Comment by cczujay** [comment]
e Placeholder (defined at \graduate\论文\DNN-DOA-master\DNN-DOA-master\ensemble_model.py:15) ]]


> Hi, Can you help me?When I run the code of main_arrayimperfactions.py,the error appears.I can hardly solve it. Help please! tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,90] [[node Placeholder (defined at \graduate\论文\DNN-DOA-master\DNN-DOA-master\ensemble_model.py:15) ]]

Hello, has your problem been solved. I have the same problem not sure how to solve it. Can you provide some ideas.

**Comment by zhimengzhou** [comment]
> I don't get that KeyError. I'm using Tensorflow 2.10.0 and used the "tf_upgrade_v2" command line script as described at https://www.tensorflow.org/guide/migrate/upgrade to migrate the code base before running. It's possible that workflow could solve your problem.

Hi. Can you share the translated code in TensorFlow 2 with me? Thanks！2043794061@qq.com or nizoukai314@gmail.com
